

type MutationResponse {
  code: String
}

type Alarm{
  name: String
  time: String
  timestamp: BigInt
  description: String
  days: [String]
  
}

input AlarmInput{

  name: String
  time: String
  timestamp: BigInt
  description: String
  days: [String]
  
}

type Query {
  getAlarms: [Alarm]
}

type Mutation{
  "Create an Alarm"
  createAlarm(alarm: AlarmInput): MutationResponse
  "update An Alarm"
  updateAlarm(id: String!, input: AlarmInput!): MutationResponse
}


# type Subscription {
#   "Listen bomb Placed on map by others players"
#   listenPlacedBombs: [Bomb]

#   "listen player game over"
#   playerUpdates: Player
# }